/**
 * Export generators — convert playground policy code into
 * ready-to-use SDK code, JSON config, and CI/CD snippets.
 */

function extractPolicyName(code: string): string {
  const match = code.match(/(?:export\s+default\s+)?function\s+(\w+)/);
  return match ? match[1] : 'myPolicy';
}

function extractPolicyDescription(code: string): string {
  const match = code.match(/\/\/\s*(.+)/);
  return match ? match[1].trim() : 'TealTiger policy';
}

export function generateTypeScript(policyCode: string): string {
  const name = extractPolicyName(policyCode);
  const desc = extractPolicyDescription(policyCode);

  return `// ${desc}
// Generated by TealTiger Playground — https://playground.tealtiger.ai

import { TealEngine, TealGuard, PolicyMode } from 'tealtiger';
import { PromptInjectionGuardrail, PIIDetectionGuardrail, ContentModerationGuardrail } from 'tealtiger';
import { ContextManager } from 'tealtiger';

// ── Policy Definition ───────────────────────────────────────────────
${policyCode}

// ── TealEngine Setup ────────────────────────────────────────────────
const engine = new TealEngine(
  {
    tools: {
      'database.query': { allowed: true, maxRows: 100 },
      'database.delete': { allowed: false },
      'file.export': { allowed: false },
    },
    content: {
      pii: { enabled: true, blockedTypes: ['ssn', 'credit_card'] },
      moderation: { enabled: true, threshold: 0.5 },
    },
    behavioral: {
      costLimit: { daily: 10, hourly: 2 },
      rateLimit: { requests: 100, window: '1m' },
    },
  },
  { mode: { default: PolicyMode.ENFORCE } }
);

// ── TealGuard Setup ─────────────────────────────────────────────────
const guard = new TealGuard({ policyDriven: true, engine });
guard.registerGuardrail(new PromptInjectionGuardrail({ sensitivity: 'high' }));
guard.registerGuardrail(new PIIDetectionGuardrail());
guard.registerGuardrail(new ContentModerationGuardrail({ useOpenAI: false }));

// ── Usage ───────────────────────────────────────────────────────────
async function handleRequest(userInput: string) {
  const ctx = ContextManager.createContext({ environment: 'production' });
  const decision = await guard.check(userInput, ctx);

  if (decision.action === 'DENY') {
    console.log('Blocked:', decision.reason_codes);
    return { error: decision.reason };
  }

  // Proceed with LLM call...
  return { allowed: true };
}

export { engine, guard, ${name} };
`;
}

export function generatePython(policyCode: string): string {
  const desc = extractPolicyDescription(policyCode);

  return `# ${desc}
# Generated by TealTiger Playground — https://playground.tealtiger.ai

from tealtiger import TealEngine, TealGuard, PolicyMode
from tealtiger.guardrails import (
    PromptInjectionGuardrail,
    PIIDetectionGuardrail,
    ContentModerationGuardrail,
)
from tealtiger.context import ContextManager

# ── Policy Configuration ─────────────────────────────────────────────
policy = {
    "tools": {
        "database.query": {"allowed": True, "max_rows": 100},
        "database.delete": {"allowed": False},
        "file.export": {"allowed": False},
    },
    "content": {
        "pii": {"enabled": True, "blocked_types": ["ssn", "credit_card"]},
        "moderation": {"enabled": True, "threshold": 0.5},
    },
    "behavioral": {
        "cost_limit": {"daily": 10, "hourly": 2},
        "rate_limit": {"requests": 100, "window": "1m"},
    },
}

# ── Engine Setup ─────────────────────────────────────────────────────
engine = TealEngine(policy, mode=PolicyMode.ENFORCE)

# ── Guard Setup ──────────────────────────────────────────────────────
guard = TealGuard(policy_driven=True, engine=engine)
guard.register_guardrail(PromptInjectionGuardrail(sensitivity="high"))
guard.register_guardrail(PIIDetectionGuardrail())
guard.register_guardrail(ContentModerationGuardrail(use_openai=False))

# ── Usage ────────────────────────────────────────────────────────────
async def handle_request(user_input: str):
    ctx = ContextManager.create_context(environment="production")
    decision = await guard.check(user_input, ctx)

    if decision.action == "DENY":
        print(f"Blocked: {decision.reason_codes}")
        return {"error": decision.reason}

    # Proceed with LLM call...
    return {"allowed": True}


# ── Original Playground Policy Logic ─────────────────────────────────
"""
${policyCode}
"""
`;
}

export function generateJSON(policyCode: string): string {
  const name = extractPolicyName(policyCode);
  const desc = extractPolicyDescription(policyCode);

  const config = {
    "$schema": "https://tealtiger.ai/schemas/policy-v1.json",
    name,
    description: desc,
    version: "1.0.0",
    mode: "ENFORCE",
    guardrails: {
      promptInjection: { enabled: true, sensitivity: "high" },
      piiDetection: { enabled: true, blockedTypes: ["ssn", "credit_card", "email"] },
      contentModeration: { enabled: true, threshold: 0.5 },
    },
    tools: {
      "database.query": { allowed: true, maxRows: 100 },
      "database.delete": { allowed: false },
      "file.export": { allowed: false },
    },
    identity: {
      role: "default",
      permissions: ["read:data"],
      forbidden: ["admin.grant", "database.drop"],
    },
    behavioral: {
      costLimit: { daily: 10, hourly: 2 },
      rateLimit: { requests: 100, window: "1m" },
    },
    _playground: {
      generatedAt: new Date().toISOString(),
      source: "https://playground.tealtiger.ai",
    },
  };

  return JSON.stringify(config, null, 2);
}

export function generateCICD(policyCode: string): string {
  const _name = extractPolicyName(policyCode);

  return `# TealTiger Policy CI/CD
# Generated by TealTiger Playground — https://playground.tealtiger.ai
#
# Add this to .github/workflows/tealtiger-policy.yml

name: TealTiger Policy Tests

on:
  pull_request:
    paths:
      - 'policies/**'
      - 'src/**/*.policy.ts'
  push:
    branches: [main]

jobs:
  policy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # Run TealTiger policy tests
      - name: Test policies
        run: npx vitest run --reporter=verbose policies/

      # Run red team benchmarks
      - name: Red team benchmark
        run: npx vitest run --reporter=verbose **/*benchmark*.test.ts

      # Lint policies
      - name: Lint policies
        run: npx eslint policies/ --ext .ts

  policy-validate:
    runs-on: ubuntu-latest
    needs: policy-test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # Validate policy schema
      - name: Validate policy config
        run: |
          node -e "
            const { TealEngine } = require('tealtiger');
            const policy = require('./policies/policy.json');
            const engine = new TealEngine(policy);
            const result = engine.validate();
            if (!result.valid) {
              console.error('Policy validation failed:', result.errors);
              process.exit(1);
            }
            console.log('Policy validation passed');
          "
`;
}
